### ISSUE TITLE
NOT WORKING !

### ISSUE THREAD

**Issue by xkajxkajx** [Stephanzion/YtDlpGui#1]
![YTD](https://github.com/user-attachments/assets/9599b9a9-6327-48c3-9c99-0a8241a7165e)

**Comment by Stephanzion** [comment]
> ![YTD](https://private-user-images.githubusercontent.com/59255771/361149142-9599b9a9-6327-48c3-9c99-0a8241a7165e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDI0NDUsIm5iZiI6MTcyNDc0MjE0NSwicGF0aCI6Ii81OTI1NTc3MS8zNjExNDkxNDItOTU5OWI5YTktNjMyNy00OGMzLTljOTktMGE4MjQxYTcxNjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA3MDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YzZmNDBlZjI0ZDQ1Y2U5ZjQwOWI5NzY1NmY3ZjRhMjcxNTA2NDgwZDEyZjI5YzI1OWU1ZWQzZDkzNDM3ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zsej_VDFGrC7NdHrfgpJWxtvo8cDiUnKNZ8durD8hnY)

Please attach a link to the video, information on whether proxies are enabled along with a screenshot of the error

**Comment by xkajxkajx** [comment]
You are right. The proxy is enabled by default . I didn't notice it because of the dark theme !

May I suggest things like:

1.Adding URL clipboard monitoring option.
2.Showing thumbnails.
3. A small progress bar showing the file size , speed of connection, downloaded and time left .
4. Adding file size in the the format list.

P.S.  In the "Save path"  option I have chosen partition (G:) but it shows it as (I:)
![ytgu](https://github.com/user-attachments/assets/a5006cae-6848-46aa-8221-e057f913335c)

Thanx

**Comment by Stephanzion** [comment]
Okay, I'll take your suggestions under advisement. I don't think point 4 is possible, as most of the formats are presented as a playlist consisting of a large number of segments, and calculating the size of each segment would take a considerable amount of time
